# Generated by Django 5.2.11 on 2026-04-07 00:18

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="nro_usuario",
            field=models.IntegerField(
                default=account.models.get_user_number, unique=True
            ),
        ),
    ]
