# Generated by Django 5.2.11 on 2026-03-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumnos",
            name="telefono",
        ),
    ]
